import { readFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";
import { readLockfile } from "../lockfile.js";
import { writeInstructions } from "../writer.js";

const HEADER = `# Copilot Instructions\n\n<!-- Generated by instruct-sync compose. Do not edit manually. -->\n\n`;
const OUTPUT = ".github/copilot-instructions.md";

export function compose(): void {
  const lock = readLockfile();
  const entries = Object.entries(lock.packs);
  if (entries.length === 0) {
    console.log("No packs installed.");
    return;
  }
  const sections: string[] = [HEADER];
  for (const [name, entry] of entries) {
    const absPath = resolve(process.cwd(), entry.target);
    if (!existsSync(absPath)) {
      console.warn(`  ⚠ skipping "${name}" — file not found at ${entry.target}`);
      continue;
    }
    const content = readFileSync(absPath, "utf8").trim();
    sections.push(`## ${name}\n\n${content}\n`);
  }
  writeInstructions(sections.join("\n"), OUTPUT);
  console.log(`✓ Composed ${entries.length} pack(s) → ${OUTPUT}`);
}
