import { readFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";
import { readLockfile } from "../lockfile.js";
import { writeInstructions } from "../writer.js";

const HEADER = `# AI Instructions\n\n<!-- Generated by instruct-sync compose. Do not edit manually. -->\n\n`;
const DEFAULT_OUTPUT = ".github/copilot-instructions.md";

export function compose(flags: { output?: string } = {}): void {
  const output = flags.output ?? DEFAULT_OUTPUT;
  const lock = readLockfile();
  const entries = Object.entries(lock.packs);
  if (entries.length === 0) {
    console.log("No packs installed.");
    return;
  }
  const sections: string[] = [HEADER];
  let composed = 0;
  for (const [key, entry] of entries) {
    const name = key.includes("@") ? key.split("@")[0] : key;
    const absPath = resolve(process.cwd(), entry.target);
    if (!existsSync(absPath)) {
      console.warn(`  ⚠ skipping "${key}" — file not found at ${entry.target}. Run: instruct-sync update`);
      continue;
    }
    const content = readFileSync(absPath, "utf8").trim();
    sections.push(`## ${name}\n\n${content}\n`);
    composed++;
  }
  writeInstructions(sections.join("\n"), output);
  if (composed < entries.length) {
    console.log(`✓ Composed ${composed} of ${entries.length} pack(s) → ${output} (${entries.length - composed} skipped — run: instruct-sync update)`);
  } else {
    console.log(`✓ Composed ${composed} pack(s) → ${output}`);
  }
}
